### ISSUE TITLE
Guide Menu is Broken

### ISSUE THREAD

**Issue by struedelmuffin** [FireEmblemUniverse/SkillSystem_FE8#110]
If you go in game, look at the guide options, restart your emulator, and then look at them again, you will notice they will be permanently messed up/hidden. This happens even on a completely unedited rom of The Sacred Stones that has only the most recent skill system installed.

**Comment by StanHash** [comment]
Couldn't reproduce the issue, the guide seems to work fine for me (that being said, your description of the issue is a bit vague so I'm not sure what I'm supposed to look for?).

**Comment by jfarr095** [comment]
Bumping this. It seems to not properly save global eIDs relating to guide entries. For context, this is using EMS. Reproduction is as stated in the OP - unlock guide entries, save game, restart, load game, check the guide again.
