### ISSUE TITLE
Paragon does not apply to Dance and Summon

### ISSUE THREAD

**Issue by VenkatSNarayanan** [FireEmblemUniverse/SkillSystem_FE8#129]
Paragon does not double the EXP gained from dances and summons.

**Comment by Peer56** [comment]
This is due to Dance, Summon and Steal giving a set amount of 10 EXP in FE8, and Paragon's code simply doesn't alter that. More of an oversight.

Although, I'm not sure if it _should_ actually boost that, how does it work in modern games eg. Fates?

**Comment by VenkatSNarayanan** [comment]
I haven't played the more modern games, but I know that in FE4 Paragon does indeed double non-combat EXP.

**Comment by sme23** [comment]
For reference, it does double dance exp in Fates
