### ISSUE TITLE
Character Level Up Skills are relearned when promoted

### ISSUE THREAD

**Issue by sme23** [FireEmblemUniverse/SkillSystem_FE8#131]
There is no way to designate a character-specific skill learned at a certain promoted level, and skills are relearned (if forgotten by reaching the equivalent level again) when promoted.

**Comment by StanHash** [comment]
Are you sure that it works like that? You should be able to specify promoted char based skills by setting the level in the list to 20 + promoted level.

**Comment by sme23** [comment]
I and others have tested this and that is not how it behaves
