### ISSUE TITLE
Prescience Skill Bugged, Adds Permanent +20 to Avoid, Misleading Stat Screen

### ISSUE THREAD

**Issue by Sokaballa** [FireEmblemUniverse/SkillSystem_FE8#215]
Prescience adds +15 Hit and +15 Avoid to statscreen permanently, but these values are purely graphic. The skill functions properly when initiating battle and does not add this bonus when defending.

However, with the Patience skill, there is a hard, permanent +20 avoid being added to units who have the skill. Made a breakdown on FeUniverse with pictures as well in the FeUniverse Skillsystems thread.

https://feuniverse.us/t/fe8-skill-system-v1-0-254-skills-done-more-on-the-way/2312/800

**Comment by sme23** [comment]
Can't reproduce the issue with Patience

**Comment by Sokaballa** [comment]
Very sorry, I have no idea why I wrote that patience was bugged. I meant to say Prescience. All of the issues were with Prescience. So sorry!!
