### ISSUE TITLE
Issues with Promo on Levelup 

### ISSUE THREAD

**Issue by TDAWS-MP132** [FireEmblemUniverse/SkillSystem_FE8#257]
Just stopping by to say I found some issues with the most recent version of skillsys while using it
specifically related to promotion on levelup
unedited it causes errors and warnings, because in the .lyn file it says 
"POIN PromoLevelList"
When it should say
"POIN PromotionLevelList"
also in the promote on levelup csv, cell 1A says 
INLINE Class_Level_Cap_Table
Which is of course the wrong table. Instead it should be 
INLINE PromotionLevelList
hope this helps

**Comment by sme23** [comment]
Doesn't appear to be a current or past issue in the master branch
