### ISSUE TITLE
Outdated Pierce glitch fix?

### ISSUE THREAD

**Issue by Huichelaar** [FireEmblemUniverse/SkillSystem_FE8#285]
[This](https://feuniverse.us/t/pierce-fix/699) seems to imply

ORG 0x59116
BYTE 0x13 0xE0

would be better than [this](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/_FE8EssentialFixes.event#L94).

**Comment by sme23** [comment]
Pierce (Vanilla)

![TVqyNfs8qW](https://user-images.githubusercontent.com/24559482/126041227-deca165f-07e2-4d64-ad2d-baa40a0da654.gif)

Pierce (Current Fix)

![PyPft1P0vV](https://user-images.githubusercontent.com/24559482/126041235-cfbb54c4-b57a-4835-af42-4f2c516f7133.gif)

Pierce (Updated Fix)

![wEsztrUqNi](https://user-images.githubusercontent.com/24559482/126041240-b67d0b94-c932-41ba-b65d-d6876ba70814.gif)

Both fixes have an identical result. The original form of the current fix had an additional change that also broke Sure Shot, but by removing that second change as circles laid out in the linked thread and as is done here it still works fine.
