### ISSUE TITLE
Mercy kills people sometimes

### ISSUE THREAD

**Issue by LeonarthCG** [FireEmblemUniverse/SkillSystem_FE8#29]
when attacking a unit that has 1 hp left, mercy will kill them, I don't know if this is intended or this was how it works in other fire emblem games, but probably not?

mercy should not be usable if no targets for attack have more than 1 hp, and it should do no damage to units with 1 hp left

**Comment by sme23** [comment]
This seems to have been fixed years ago by circles with 13c1d9b46be3ffce186916c9b694558642f18143 and just never closed
