### ISSUE TITLE
Enemy proccing Sol doesn't display skill animation.

### ISSUE THREAD

**Issue by Huichelaar** [FireEmblemUniverse/SkillSystem_FE8#300]
Breguet here is triggering Sol, yet the "SOL" animation doesn't play.

![2021-09-25_23-22-42](https://user-images.githubusercontent.com/76848124/134796190-f4712dff-3f26-44d2-9d27-6157029db0f1.gif)

It seems to happen as a result of AISRelatedShorts not having a certain flag (0x800) set which command 7 in battle animations checks to play skill animations.

**Comment by sme23** [comment]
oh i only saw that it fixed #270 , it does also fix this one so yeah issue can be closed
