### ISSUE TITLE
Barricade needs help

### ISSUE THREAD

**Issue by Snakey11** [FireEmblemUniverse/SkillSystem_FE8#343]
Sme brought up proc loop things being weird in https://github.com/FireEmblemUniverse/SkillSystem_FE8/issues/342#issue-1111762619, so I may as well confess my sins.
In https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/2f61d56d63b678ac989bbeecb0202c934249eb38/EngineHacks/Necessary/CalcLoops/BattleProcCalcLoop/ProcStart/proc_start.s#L70
I made an assumption of `r11` being untouched throughout the proc loop (which seems like a fairly safe assumption because it hasn't broken yet, but it's probably a matter of time before something bad happens). This should be changed, and while someone (preferably future me) is at it, the code here should probably be shuttled to a subroutine that lives in barricade's area in `EngineHacks/SkillSystem/...`.

Am bad wizard confirmed, sorry for bad code, just thought I'd document this.

**Comment by sme23** [comment]
going to just say "don't use r11 in proc loop funcs" as a specification and leave this as-is, very complicated solution to a non-issue to change how this works
