### ISSUE TITLE
proc_finish considers damage as healing due to not loading a value as signed.

### ISSUE THREAD

**Issue by Huichelaar** [FireEmblemUniverse/SkillSystem_FE8#346]
Maybe the comments are confusing me, but I think this byte value should be loaded as a signed byte.
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/4eb6c724c6581822e25e09bdf263d16aa0d7e1ad/EngineHacks/Necessary/CalcLoops/BattleProcCalcLoop/ProcFinish/proc_finish.s#L57

Also, a positive value in +0x5 is seen as damage in this routine, but seems to represent healed HP.

**Comment by Huichelaar** [comment]
When Breguet gets hurt by Lute it seems his CounterMagic doesn't inflict damage because of this. Can you reproduce this issue?

**Comment by Huichelaar** [comment]
Nosferatu Doesn't seem to play nice with this.

https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/4b5edd28ef8a528181442c0d1b6f61543dcbec2b/EngineHacks/SkillSystem/Internals/HPHealing.event#L17

The damage dealt is in +0x3, but [+0x5] is still 0, even when the attacker should heal. I'm assuming [+0x5] is 0 because Nosferatu wasn't modified to store healed HP in +0x5.

**Comment by Huichelaar** [comment]
r2 holds the damage dealt. I think what should be stored is the difference between the old and new HP, which might be less than damage dealt due to HP capping.
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/4b5edd28ef8a528181442c0d1b6f61543dcbec2b/EngineHacks/SkillSystem/Skills/ProcSkills/LifeSteal/proc_stealhp.s#L120

**Comment by sme23** [comment]
> When Breguet gets hurt by Lute it seems his CounterMagic doesn't inflict damage because of this. Can you reproduce this issue?

Lute, and any magic user vs. Breguet for that matter, are properly taking damage from Countermagic, so I cannot reproduce this.
Both Sol and Aether are working as intended vs. Counter & Countermagic (don't heal or take damage), but Nosferatu specifically does seem to be behaving incorrectly.

**Comment by Huichelaar** [comment]
I can't reproduce the CounterMagic issue I mentioned before.  I probably did something weird on my branch.
