### ISSUE TITLE
Combat Art Adept Flag Conflict

### ISSUE THREAD

**Issue by JacobTJP** [FireEmblemUniverse/SkillSystem_FE8#356]
The adept combat art, which uses the value 6 by default in 0x0203F101, will increase the attack upon use by a large (though currently undetermined) amount. Setting the flag to a different value fixes this so I believe there to be a conflict somewhere causing this to occur.

![image](https://user-images.githubusercontent.com/42071732/158182183-93de4363-b7b9-410a-ae76-40e62b3bafee.png)

**Comment by sme23** [comment]
FYI this was caused by the table for ModularPreBattleSkills, if you don't want to use that turn it off in Config.event and it should stop doing this
