### ISSUE TITLE
Narrow font issue

### ISSUE THREAD

**Issue by dood6020** [FireEmblemUniverse/SkillSystem_FE8#358]
The lowercase T becomes a question mark ingame.
![Screenshot (129)](https://user-images.githubusercontent.com/82291635/159143078-94a5d934-b532-49fc-8ff5-2e14c8030ab5.png)
![fe8 prequel emulator-2](https://user-images.githubusercontent.com/82291635/159143029-e28ea7af-bf7c-4b5d-b427-65df299e265d.png)

**Comment by sme23** [comment]
This is an FEBuilder issue, not a skill system issue
