### ISSUE TITLE
Using CLEE while an enemy is being captured does not unset the capture on the player unit

### ISSUE THREAD

**Issue by Pikmin1211** [FireEmblemUniverse/SkillSystem_FE8#384]
The enemy is cleared from the unit array but the player unit is still capturing and still has their ID set as the capturee. This means trying to trade with that unit causes a crash.

10426: CLEE

Suggestion: 
Hook ClearUnit to make it clear the rescuee from the rescuer (I'm surprised vanilla doesnt do this. Does CLEN while you are rescuing a green unit also bug out?)

**Comment by sme23** [comment]
It's a vanilla bug, [this](https://cdn.discordapp.com/attachments/894721150511374437/997349691039686816/NewClearUnit.7z) is a fix, going to close this for now since its a vanilla FE8 issue and potentially add the fix later
