### ISSUE TITLE
Enemy units not getting cleared from RAM

### ISSUE THREAD

**Issue by LeonarthCG** [FireEmblemUniverse/SkillSystem_FE8#48]
People are reporting that enemy units are not being erased from RAM when they die, this is causing danger zone to not work properly and dead units are preventing new ones from spawning in.

**Comment by StanHash** [comment]
From what I recall, this is caused (and thus was introduced) by capture; and was fixed by Teq for FETD2 but not ported back into the skill system itself yet. (@LNB2017)

**Comment by StanHash** [comment]
Was fixed by #49
