### ISSUE TITLE
I'm a dummy, plz help.

### ISSUE THREAD

**Issue by Daniel-ags** [FireEmblemUniverse/SkillSystem_FE8#484]
I know it probably is a super dumb question, but how can i get a Str/Mag split? I know how to patch it, but i can't find a file...

Edit: I found out that the skill system already has that functionality, but how do i activate it?

**Comment by GigaExcalibur** [comment]
The Str/Mag split, along with many other options, can be found in EngineHacks/Config.event. See this link for information on how to use Skillsys for your specific purposes: https://feuniverse.us/t/the-skill-system-and-you-maximizing-your-usage-of-fe8s-most-prolific-bundle-of-wizardry/8232
