### ISSUE TITLE
Galeforce autoselect fails when standing on terrain that was only possible to traverse due to acrobat 

### ISSUE THREAD

**Issue by Veslyquix** [FireEmblemUniverse/SkillSystem_FE8#504]
A playtester noticed this for me, lol. 

The autoselect code doesn't account for acrobat / isn't hooked for acrobat. It's very much a fringe case, but might be nice to eventually make a calc loop for skills that adjust terrain cost. 

Vanilla does this around: 
// at 801D28E it calls CanActiveUnitMove 0x8018BD8

**Comment by sme23** [comment]
"solves" apparently isn't an autoresolve keyword, reee
