### ISSUE TITLE
UTF-8 Opening Quote menu character needed

### ISSUE THREAD

**Issue by GigaExcalibur** [FireEmblemUniverse/SkillSystem_FE8#550]
Hey there, sorry to be a bother. A while ago I discovered that Skillsys' UTF-8 font support doesn't have an associated character for (among other things) a pair of opening quotes in the menu font. I didn't write this as an issue back then because I could compromise with single quotes, but now I've come across a more general use case and think it's a necessity.

**Comment by sme23** [comment]
fixed by #601
