### ISSUE TITLE
Rescue debuff arrows incorrectly positioned.

### ISSUE THREAD

**Issue by GigaExcalibur** [FireEmblemUniverse/SkillSystem_FE8#564]
I'm surprised nobody's caught this before. When you rescue a unit and you have the Str/Mag split enabled, the rescuing debuff arrows are drawn next to Magic and Skill despite it halving Skill and Speed.

![image](https://github.com/FireEmblemUniverse/SkillSystem_FE8/assets/118407413/cfa95394-0cef-4d3d-92ab-65cb48f9a971)

Since we have the power to halve any stat we want while rescuing (thank you Stat Getters) the rescuing debuff arrows should be modularized (or outright removed, as the big `-4` next to the stat bar already communicates that the stat is debuffed). Regardless this isn't gamebreaking but now that I've noticed it I can't unsee it.

**Comment by sme23** [comment]
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/2f741f1658de7a5c5e08d0e3107ea0ace6a1e3da/EngineHacks/Necessary/ModularStatScreen/ModularStatScreen.event#L11-L16 this lets you change their locations for your layout, but it should set automatically if strmag; this may be doable with just #ifdefs
