### ISSUE TITLE
Change initial FreeSpace definition to 0x100 0000.

### ISSUE THREAD

**Issue by Huichelaar** [FireEmblemUniverse/SkillSystem_FE8#566]
I suggest we change the initial FreeSpace offset to 0x100 0000 or wherever FE8U's ROM meaningfully ends. I've seen people cross through the initial FreeSpace block between 0xb2 a610 and 0xc0 0000 a number of times without having any idea what that means. I think it'd be less overhead to fill people who've managed to fill their project and are looking for a way to save space in, than informing people who've just started and aren't yet familiar with EA or FE8U's internal structure. Odds are people will not reach that 0x200 0000 limit when working on a buildfile project anyways.

Comment out this line (with maybe an extra comment giving more clarity on why it's here):
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/CustomDefinitions.event#L1

Add a new `#define FreeSpace 0x1000000` line.

Thoughts?

**Comment by sme23** [comment]
fixed by #569
