### ISSUE TITLE
Corona Bug

### ISSUE THREAD

**Issue by ZeikoLeMonde** [FireEmblemUniverse/SkillSystem_FE8#592]
If unit is wielding a tome, Corona skips the skill check (and the animation), and always grants its effect.

**Comment by sme23** [comment]
Sounds like a tome with Corona set on it as a skill. Can't reproduce

**Comment by ZeikoLeMonde** [comment]
There is a `beq NegateDefenses` in line 49 of proc_corona.s that makes it skip straight to line 78 if the unit is using a weapon with the weapon ability bit 0x00000002 (is magic weapon), skipping the activation rate part (lines 55-59) and the part where the offensive skill flag is set (lines 61-74). This does not happen if using a weapon with the weapon ability bit 0x00000040 (is magic sword).
