### ISSUE TITLE
Movement skills bug

### ISSUE THREAD

**Issue by ZeikoLeMonde** [FireEmblemUniverse/SkillSystem_FE8#593]
Certain movement skills (ie: Keep Up, Nature Rush) will not apply the bonus movement unless the player checks the status screen first.

**Comment by sme23** [comment]
These skills work off the same system as armor march, which is responsible for clearing the relevant effect bit at the start of each turn. The addition of the start of turn calc loop broke non-armor march skills that use that bit for their effect by now only checking them when the pre-battle calc loop runs, which happens whenever battle stats are calculated, such as when the stat screen is opened. they need to be moved here instead
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/b8f6b89cdec9a435ce3c403c674e552805060672/EngineHacks/Necessary/CalcLoops/TurnLoop/Installer.event#L12-L13
