### ISSUE TITLE
Eclipse Skill Bug

### ISSUE THREAD

**Issue by ZeikoLeMonde** [FireEmblemUniverse/SkillSystem_FE8#594]
Eclipse calculates damage using the byte 0x72 of the battle struct. However, this byte doesn't contain current HP, but "Current HP at the start of the battle". As a result, if the target lost HP in that same battle before Eclipse triggered, then, instead of leaving the target with 1 HP, it will kill them.

**Comment by sme23** [comment]
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/b8f6b89cdec9a435ce3c403c674e552805060672/EngineHacks/SkillSystem/Skills/ProcSkills/Bane/proc_bane.s#L45-L51 would be the correct way to do the check
