### ISSUE TITLE
Items don't drop on enemy phase

### ISSUE THREAD

**Issue by beccarte** [FireEmblemUniverse/SkillSystem_FE8#60]
In my hands, if an enemy with a droppable item attacks you and dies, the item does not drop.

**Comment by StanHash** [comment]
Could replicate and can also confirm it is caused by https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/Engine%20Hacks/Skill%20System/Teq%20Skills/FE8-Capture/FE8-Capture/FE8-Capture%20EA.txt#L48.
