### ISSUE TITLE
Anim Number issue

### ISSUE THREAD

**Issue by MokhaLeee** [FireEmblemUniverse/SkillSystem_FE8#604]
https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/ExternalHacks/AnimNumbers/asm/DisplayDamage.s#L48

BattleStats+4 = damage
BattleStats+6 = attack

Here we need to display damage rather than attack, but here it use `BattleStats::attack`. why?

**Comment by Huichelaar** [comment]
This is done to show damage that would have been dealt if the recipient had HP >= damage. It's purely for display.
