### ISSUE TITLE
Current HP Issues

### ISSUE THREAD

**Issue by masterofcontroversy** [FireEmblemUniverse/SkillSystem_FE8#685]
`TryUnitHeal` gets modified by [InjectHPGetters.event](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/d5d47d6bacc3f5decb553a69c7eb64d957467ab0/EngineHacks/Necessary/MSG/3rdParty/InjectHPGetters.event#L24-L29) and as a result replaces the section of code that floors current HP at 0.
This allows `TryUnitHeal` to write negative current HP values to unit structs.

Rather than using the current HP getter, the post-action calcloop uses current HP that was loaded directly from the unit struct before [this hook](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/d5d47d6bacc3f5decb553a69c7eb64d957467ab0/EngineHacks/Necessary/CalcLoops/PostActionCalcLoop/PostActionCalcLoop.event#L5).
Should the loaded value be negative, [this check](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/d5d47d6bacc3f5decb553a69c7eb64d957467ab0/EngineHacks/Necessary/CalcLoops/PostActionCalcLoop/PostActionCalcLoop.s#L13-L14) will pass and unset the hidden bit, even when a unit should be dead.

This can be observed by killing a unit with a trap, as shown here (A mine is used for the test):
![Mine](https://github.com/user-attachments/assets/03d5e3a2-2df5-490b-bf7f-2050d72f9ffc)

**Comment by Veslyquix** [comment]
Iirc this is also used by poison, so it should be tested as well. I recall replacing TryUnitHeal in my project, but I also made poison unable to kill.
