### ISSUE TITLE
Adept Activation + Skill Learning in same battle = crash?

### ISSUE THREAD

**Issue by boviex** [FireEmblemUniverse/SkillSystem_FE8#8]
investigate further

**Comment by sme23** [comment]
I've attempted multiple times over multiple years to reproduce this and have been wholly unsuccessful, it's likely that when Skill Learning was changed to use Popup Rework with a3cd59e12184ebfc5ae2fac34659829679535ab6 this was fixed. If someone can reliably reproduce this crash, I will reopen the issue.
